version: "3.5"
services:

  zookeeper:
    image: debezium/zookeeper:1.4
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    deploy:
      mode: global

  kafka:
    image: debezium/kafka:1.4
    ports:
      - "9092:9092"
    deploy:
      mode: global  
    depends_on:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    ports:
      - "9200:9200"
    deploy:
      mode: global  
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin=*  

  connect:
    build: ./debezium-jdbc-es
    ports:
      - "8083:8083"
      - "5005:5005"
    deploy:
      mode: global  
    depends_on:
      - kafka
      - elasticsearch
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_source_connect_statuses

    